services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: rssagg
      POSTGRES_USER: rssagg
      POSTGRES_PASSWORD: rssaggpass
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./sql/schema:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rssagg -d rssagg"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    restart: unless-stopped
    environment:
      PORT: "8080"
      DB_URL: "postgresql://rssagg:rssaggpass@db:5432/rssagg?sslmode=disable"
    depends_on:
      db:
        condition: service_healthy

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - app

volumes:
  dbdata:


